Repository RedHatOfficial/ocp4-helpernode, pull requests merged in 2020-07, with the labels that each got.

#94 Mirror ppc64le NFS image to local registry and Fix registry_host undefined bug
  tasks/setup_registry.yaml
  templates/nfs-provisioner-deployment.yaml.j2
  templates/zonefile.j2
Labels: testing

#99 Fix issue #91 regarding the default pxelinux.cfg file
  docs/vars-doc.md
  tasks/main.yml
Labels: testing

#100 Move out set facts for local registry to overall env
  tasks/set_facts_.yaml
Labels: testing

#117 Updated image for disconnected to point to 4.5.2
  vars/main.yml
Labels: hotfix, testing

#120 Update main.yml
  docs/examples/vars-local-registry-ppc64le.yaml
  docs/examples/vars-ppc64le.yaml
  tasks/main.yml
Labels: testing

#124 post-run local registry info
  tasks/setup_registry.yaml
  templates/checker.sh.j2
Labels: testing

#127 Compact cluster support
  docs/bmquickstart-static.md
  docs/bmquickstart.md
  docs/examples/vars-compact-static.yaml
  docs/examples/vars-compact.yaml
  docs/iso-maker.md
  docs/quickstart-powervm.md
  docs/quickstart-ppc64le.md
  docs/quickstart-static.md
  docs/quickstart.md
  docs/vars-doc.md
  tasks/generate_ssh_keys.yaml
  tasks/main.yml
  tasks/setup_registry.yaml
  tasks/validate_host_names.yaml
  templates/checker.sh.j2
  templates/default.j2
  templates/dhcpd.conf.j2
  templates/haproxy.cfg.j2
  templates/nfs-provisioner-deployment.yaml.j2
  templates/pxe-bootstrap.j2
  templates/pxe-master.j2
  templates/pxe-worker.j2
  templates/reverse.j2
  templates/zonefile.j2
Labels: WIP, enhancement, pending review, testing
